spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blc_pass?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: DB_USERNAME
    password: DB_PASSWORD
#  rabbitmq:
#    host: localhost
#    port: 5672
#    password: password
#    username: admin

network:
  resource:
    url: NETWORK_RESOURCE_DIR:./runtime/networks

aliyun:
  oss:
    accesskey: ${ALIYUN_OSS_ACCESS_KEY:}
    secretkey: ${ALIYUN_OSS_SECRET_KEY:}
    endpoint: ${ALIYUN_OSS_ENDPOINT:}
